on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
jobs:
  build:
    name: send rss message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/line-action@master
      with:
        secret: ${{ secrets.LINE_CHANNEL_SECRET }}
        token: ${{ secrets.LINE_CHANNEL_TOKEN }}
        args: line message from GitHub Actions ${{on.rss.outputs.title}}
